apiVersion: apps/v1
kind: Deployment
metadata:
  name: hayy-api-staging
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hayy-api-staging
  template:
    metadata:
      labels:
        app: hayy-api-staging
    spec:
      containers:
      - name: api
        image: ghcr.io/arpit529srivastava/hayy-ai-backend-stag:staging
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: hayy-api-staging-secrets
              key: NODE_ENV
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: hayy-api-staging-secrets
              key: PORT
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: hayy-api-staging-secrets
              key: MONGODB_URI
      nodeSelector:
        eks.amazonaws.com/compute-type: fargate
      tolerations:
      - key: eks.amazonaws.com/compute-type
        operator: Equal
        value: fargate
        effect: NoSchedule
